language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: tech-conferences.surge.sh
  project: ./build/
on:
  branch: master
